config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cats
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
require 'action_view'
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    COLORS = 
    [
        'black', 
        'white', 
        'orange', 
        'brown'
    ].freeze 

    validates_presence_of :birth_date, :color, :name, :sex, :description
    validates_inclusion_of :color, in: COLORS
    validates_inclusion_of :sex, in: %w(M F)
    
    def age
        time_ago_in_words(birth_date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all

        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])

        if @cat
            render :show
        else
            redirect_to cats_url
        end

    end

    def new
        @cat = Cat.new

        render :new
    end

    def edit
        @cat = Cat.find_by_id(params[:id])

        if @cat
            render :edit
        else
            redirect_to cats_url
        end
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
          redirect_to cat_url(@cat)
        else
          render :new
        end
    end

    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update(cat_params)
          redirect_to @cat
        else
          render :edit
        end
    end
    

    private
    def cat_params
        params.require(:cat).permit(:name, :description, :birth_date, :sex, :color)
    end
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% action_url = @cat.persisted? ? edit_cat_url(@cat) : cats_url %>
<% submit_text = @cat.persisted? ? "Update a Cat!" : "Add a new Cat!" %>

<form action="<%= action_url%>" method="post">
    
    <% if  @cat.persisted?%>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>
    
    <label for="name">Cat Name</label>
    <input type="text" name="cat[name]" id="name" value="<%= @cat.name %>">

    <br><br>

    <label for="cat_color">Cat Color</label>
    <select name="cat[color]" id="cat_color">
        <option disabled selected>--Select a Color--</option>
        
        <% Cat::COLORS.each do |color| %>
            <option value="<%= color %>" <%= @cat.color == color ? "selected" : "" %>>
            <%= color.upcase %>
            </option>
        <% end %>
        
    </select>

    <br><br>

    <label for="birth_date">Birth-Date</label>
    <input type="date" name="cat[birth_date]" id="birth_date" value="<%= @cat.birth_date %>">
    <br><br>

    <label for="cat_description">Cat Description</label>
    <textarea name="cat[description]" id="cat_description">
        <%= @cat.description %>
    </textarea>
    <br><br>


    <label for="male">Male</label>
    <input
        type="radio" 
        name="cat[sex]" 
        id="male" 
        value='M' 
        <%= @cat.sex == "M" ? "checked" : "" %>
        >
    <label for="female">Female</label>
    <input <%= @cat.sex == 'F' ? 'checked' : "" %>
        type="radio" 
        name="cat[sex]" 
        id="female" 
        value='F' >

    <br><br>

    <button type="submit"><%= submit_text %></button>


</form>

app/views/cats/edit.html.erb
<h1>Edit <%= @cat.name %> Cat</h1>

<%= render 'cats/form' %>

app/views/cats/index.html.erb
<h1>List of Cats</h1>


<ul>
    <% @cats.each do |cat| %>
        <li><%= cat.name %></li>
        <%= link_to 'Show this cat', cat_url(cat) %>
    <% end %>
</ul>

app/views/cats/new.html.erb
<h1>Add new Cat</h1>

<%= render 'cats/form' %>

app/views/cats/show.html.erb
<h3><%= @cat.name %> Info</h3>

<h5>Name: <%= @cat.name %></h5>
<h5>Age: <%= @cat.age %></h5>
<h5>Birthdate: <%= @cat.birth_date %></h5>
<h5>Color: <%= @cat.color.capitalize %></h5>
<h5>Description: <%= @cat.description %></h5>
<h5>Sex: <%= @cat.sex == 'F' ? 'Female' : "Male" %></h5>

<table>
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Birthdate</th>
        <th>Color</th>
        <th>Sex</th>
        <th>Description</th>
    </tr>

    <tr>
        <td><%= @cat.name %></td>
        <td><%= @cat.age %></td>
        <td><%= @cat.birth_date %></td>
        <td><%= @cat.color.capitalize %></td>
        <td><%= @cat.sex == "F" ? "Female" : "Male"%></td>
        <td><%= @cat.description %></td>
    </tr>
</table>

<%= link_to 'Edit cat', edit_cat_url(@cat) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>